name: AA_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipython
  - jupyter
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scienceplots
  - scipy
  - scikit-learn
  - scikit-fda
  - graphviz
  - python-graphviz
  - py-xgboost
  - pip:
    - sidetable
    - torch
    - keras
    - nltk
    - aquarel
